import PgBoss from "pg-boss";
import { eq } from "drizzle-orm";
import { documents, companies, customFields, extractions, fieldValues } from "@copyr/db/schema.js";
import type { FieldSpec } from "@copyr/ai";
import { and } from "drizzle-orm";
import type { CoreContext } from "../context.js";
import { logActivity } from "../activity.js";
import { spendCredits } from "../credits.js";
import { makePdf, wrapText } from "../utils/pdf.js";
import { setFieldValues } from "../services/fields.js";
import type { Session } from "../context.js";

const SYSTEM_SESSION = (workspaceId: string): Session => ({
  workspaceId,
  actor: { userId: null, source: "agent" },
});

export async function parseDocumentJob(ctx: CoreContext, data: { workspaceId: string; documentId: string }) {
  const [doc] = await ctx.db
    .select()
    .from(documents)
    .where(and(eq(documents.id, data.documentId), eq(documents.workspaceId, data.workspaceId)));
  if (!doc) return;

  await ctx.db.update(documents).set({ parseStatus: "parsing" }).where(eq(documents.id, doc.id));
  try {
    if (!doc.storageKey) throw new Error("document has no stored file yet");
    const bytes = await ctx.storage.get(doc.storageKey);
    let textContent = "";
    let pageCount: number | null = null;

    if (doc.mime.includes("pdf")) {
      const { extractText, getDocumentProxy } = await import("unpdf");
      const pdf = await getDocumentProxy(new Uint8Array(bytes));
      const result = await extractText(pdf, { mergePages: true });
      textContent = result.text ?? "";
      pageCount = pdf.numPages;
    } else {
      textContent = bytes.toString("utf8").slice(0, 100_000);
    }

    await ctx.db
      .update(documents)
      .set({ parseStatus: "parsed", textContent: textContent.slice(0, 200_000), pageCount })
      .where(eq(documents.id, doc.id));

    await logActivity(ctx, ctx.db, {
      workspaceId: data.workspaceId,
      entityType: "document",
      entityId: doc.id,
      companyId: doc.companyId,
      dealId: doc.dealId,
      type: "document.parsed",
      summary: `Parsed "${doc.name}" (${pageCount ?? "?"} pages)`,
      actor: "system",
    });

    // auto-extract after parsing
    await runExtractionForDocument(ctx, data.workspaceId, doc.id);
  } catch (err) {
    await ctx.db
      .update(documents)
      .set({ parseStatus: "failed", parseError: err instanceof Error ? err.message : String(err) })
      .where(eq(documents.id, doc.id));
    await logActivity(ctx, ctx.db, {
      workspaceId: data.workspaceId,
      entityType: "document",
      entityId: doc.id,
      companyId: doc.companyId,
      dealId: doc.dealId,
      type: "document.parse_failed",
      summary: `Failed to parse "${doc.name}"`,
      actor: "system",
      data: { error: err instanceof Error ? err.message : String(err) },
    });
  }
}

/**
 * Mock/first-pass link converter. Attempts a metadata fetch; falls back to a
 * synthetic PDF derived from the URL. Produces a real stored PDF either way.
 */
export async function convertLinkJob(ctx: CoreContext, data: { workspaceId: string; documentId: string }) {
  const [doc] = await ctx.db
    .select()
    .from(documents)
    .where(and(eq(documents.id, data.documentId), eq(documents.workspaceId, data.workspaceId)));
  if (!doc || !doc.sourceUrl) return;

  await ctx.db.update(documents).set({ parseStatus: "converting" }).where(eq(documents.id, doc.id));

  try {
    const url = new URL(doc.sourceUrl);
    let title = decodeURIComponent(url.pathname.split("/").filter(Boolean).pop() ?? url.hostname);
    const bodyLines: string[] = [];

    try {
      const res = await fetch(url.toString(), {
        headers: { "user-agent": "CopyrBot/0.1 (+https://copyr.dev)" },
        signal: AbortSignal.timeout(8_000),
      });
      const html = res.ok ? await res.text() : "";
      title =
        html.match(/<title[^>]*>([^<]{1,160})<\/title>/i)?.[1]?.trim() ||
        html.match(/<meta[^>]+property="og:title"[^>]+content="([^"]{1,160})"/i)?.[1] ||
        title;
      const desc =
        html.match(/<meta[^>]+name="description"[^>]+content="([^"]{1,400})"/i)?.[1] ?? "";
      bodyLines.push(`Converted from: ${url.toString()}`);
      if (desc) bodyLines.push("", ...wrapText(desc));
    } catch {
      bodyLines.push(`Converted from: ${url.toString()}`);
      bodyLines.push("(Live fetch unavailable in this environment — synthetic conversion.)");
    }

    const pdfBytes = makePdf(
      title,
      [
      "",
      `Source: ${url.toString()}`,
      `Provider: ${url.hostname.replace("www.", "")}`,
      `Converted at: ${new Date().toISOString()}`,
      "",
      ...bodyLines,
      "",
      "This permanent copy was generated by Copyr so the original link can never expire.",
      ].join("\n"),
    );

    const key = `workspaces/${data.workspaceId}/documents/${crypto.randomUUID()}.pdf`;
    await ctx.storage.put(key, pdfBytes, "application/pdf");

    await ctx.db
      .update(documents)
      .set({
        storageKey: key,
        mime: "application/pdf",
        sizeBytes: pdfBytes.byteLength,
        parseStatus: "parsed",
        textContent: `${title}\n${bodyLines.join("\n")}`.slice(0, 50_000),
        pageCount: 1,
      })
      .where(eq(documents.id, doc.id));

    await logActivity(ctx, ctx.db, {
      workspaceId: data.workspaceId,
      entityType: "document",
      entityId: doc.id,
      companyId: doc.companyId,
      dealId: doc.dealId,
      type: "document.parsed",
      summary: `Converted "${url.hostname}" link to permanent PDF`,
      actor: "ai",
    });

    await runExtractionForDocument(ctx, data.workspaceId, doc.id);
  } catch (err) {
    await ctx.db
      .update(documents)
      .set({ parseStatus: "failed", parseError: err instanceof Error ? err.message : String(err) })
      .where(eq(documents.id, doc.id));
    throw err;
  }
}

/** AI deck extraction → fill empty fields on company/deal. */
export async function runExtractionForDocument(
  ctx: CoreContext,
  workspaceId: string,
  documentId: string,
): Promise<void> {
  const [doc] = await ctx.db
    .select()
    .from(documents)
    .where(and(eq(documents.id, documentId), eq(documents.workspaceId, workspaceId)));
  if (!doc?.textContent || !doc.companyId) return;

  const [company] = await ctx.db.select().from(companies).where(eq(companies.id, doc.companyId));
  if (!company) return;
  const deal = company;

  const [extraction] = await ctx.db
    .insert(extractions)
    .values({
      workspaceId,
      kind: "deck",
      status: "running",
      documentId: doc.id,
      companyId: doc.companyId,
      dealId: deal?.id ?? null,
      model: ctx.ai.model,
    })
    .returning();

  try {
    const specs = await ctx.db
      .select()
      .from(customFields)
      .where(and(eq(customFields.workspaceId, workspaceId), eq(customFields.aiExtractable, true)));
    // deck text describes the company; only company-target fields are fillable here
    const fieldSpecs: FieldSpec[] = specs
      .filter((s) => s.target === "company")
      .map((s) => ({
        key: s.key,
        label: s.label,
        type: s.type,
        options: s.options,
      }));

    const output = await ctx.ai.extractDeck(doc.textContent, fieldSpecs);

    // apply: only fill EMPTY values (never clobber human input)
    const session = SYSTEM_SESSION(workspaceId);
    await ctx.db.transaction(async (tx) => {
      await spendCredits(ctx, tx as never, workspaceId, "deck_extraction", {
        refType: "extraction",
        refId: extraction.id,
      });

      const existingValues = await tx
        .select({ key: customFields.key, value: fieldValues.value })
        .from(fieldValues)
        .innerJoin(customFields, eq(fieldValues.fieldId, customFields.id))
        .where(and(eq(fieldValues.entityType, "company"), eq(fieldValues.entityId, doc.companyId!)));
      const filled = new Set(existingValues.filter((v) => v.value !== null && v.value !== undefined).map((v) => v.key));

      const toSet: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(output.fields)) {
        if (value !== null && value !== undefined && !filled.has(key)) toSet[key] = value;
      }
      if (Object.keys(toSet).length) {
        await setFieldValues(ctx, tx as never, session, "company", doc.companyId!, toSet as never, { confidence: output.confidence });
      }

      const companyPatch: Record<string, unknown> = {};
      for (const k of ["sector", "location", "description"] as const) {
        const v = output.company[k];
        if (v && !company[k]) companyPatch[k] = v;
      }
      if (output.company.foundedYear && !company.foundedYear) companyPatch.foundedYear = output.company.foundedYear;
      if (output.company.employeeCount && !company.employeeCount) companyPatch.employeeCount = output.company.employeeCount;
      if (output.company.domain && !company.domain) companyPatch.domain = output.company.domain;
      if (Object.keys(companyPatch).length) {
        await tx.update(companies).set(companyPatch).where(eq(companies.id, doc.companyId!));
      }

      if (deal) {
        const dealPatch: Record<string, unknown> = {};
        if (output.deal.roundStage && !deal.roundStage) dealPatch.roundStage = output.deal.roundStage;
        if (output.deal.askAmountUsd != null && deal.askAmount === null) {
          dealPatch.askAmount = String(output.deal.askAmountUsd);
        }
        if (Object.keys(dealPatch).length) {
          await tx.update(companies).set(dealPatch).where(eq(companies.id, deal.id));
        }
      }

      await tx
        .update(extractions)
        .set({
          status: "completed",
          result: { ...output.fields, company: output.company, deal: output.deal },
          confidence: String(output.confidence),
          completedAt: new Date(),
        })
        .where(eq(extractions.id, extraction.id));

      await logActivity(ctx, tx, {
        workspaceId,
        entityType: "company",
        entityId: doc.companyId!,
        companyId: doc.companyId,
        dealId: deal?.id ?? null,
        type: "extraction.completed",
        summary: `AI extracted ${Object.keys(output.fields).length} field(s) from "${doc.name}"`,
        actor: "ai",
        data: { extractionId: extraction.id, confidence: output.confidence, fields: Object.keys(output.fields) },
      });
    });
  } catch (err) {
    await ctx.db
      .update(extractions)
      .set({
        status: "failed",
        error: err instanceof Error ? err.message : String(err),
        completedAt: new Date(),
      })
      .where(eq(extractions.id, extraction.id));
    throw err;
  }
}

/* ── worker wiring ─────────────────────────────────────────────────── */

export async function startWorkers(ctx: CoreContext, boss: PgBoss, concurrency: number): Promise<void> {
  await boss.createQueue("process-email");
  await boss.createQueue("parse-document");
  await boss.createQueue("convert-link");
  await boss.createQueue("run-review-table");
  await boss.createQueue("run-agent");
  await boss.createQueue("agent-scheduler-tick");
  await boss.createQueue("run-workflows");
  await boss.createQueue("webhook-deliver");

  // fan every emitted activity out to automations + outbound webhooks.
  // The activity insert and its pg_notify commit atomically (logActivity),
  // so this subscriber sees exactly-committed events exactly once per emit.
  await ctx.bus.subscribe((payload) => {
    try {
      const event = JSON.parse(payload) as { workspaceId: string; data?: Record<string, unknown> };
      if ((event.data as Record<string, unknown> | undefined)?.__wf) return; // workflow-originated
      void ctx.enqueue("run-workflows", { event });
      void import("../services/outbound.js").then((m) =>
        m.dispatchEventToWebhooks(ctx, event as never).catch(() => undefined),
      );
    } catch {
      // malformed payload — skip
    }
  });

  await boss.work("process-email", { batchSize: 1, pollingIntervalSeconds: 1 }, async (jobs) => {
    for (const job of jobs) {
      const d = job.data as { workspaceId: string; emailId: string };
      const { processEmailMessage } = await import("../services/emails.js");
      await processEmailMessage(ctx, d.workspaceId, d.emailId);
    }
  });

  await boss.work("parse-document", { batchSize: concurrency, pollingIntervalSeconds: 1 }, async (jobs) => {
    for (const job of jobs) {
      await parseDocumentJob(ctx, job.data as { workspaceId: string; documentId: string });
    }
  });

  await boss.work("run-workflows", { batchSize: concurrency, pollingIntervalSeconds: 1 }, async (jobs) => {
    for (const job of jobs) {
      const d = job.data as { event: Parameters<typeof import("../services/automation.js").evaluateWorkflowsForEvent>[1] };
      const { evaluateWorkflowsForEvent } = await import("../services/automation.js");
      await evaluateWorkflowsForEvent(ctx, d.event).catch((err) => {
        console.error("[run-workflows]", err instanceof Error ? err.message : err);
      });
    }
  });

  await boss.work("webhook-deliver", { batchSize: concurrency, pollingIntervalSeconds: 2 }, async (jobs) => {
    for (const job of jobs) {
      const d = job.data as { deliveryId: string };
      const { deliverWebhook } = await import("../services/outbound.js");
      await deliverWebhook(ctx, d.deliveryId);
    }
  });

  await boss.work("convert-link", { batchSize: concurrency, pollingIntervalSeconds: 1 }, async (jobs) => {
    for (const job of jobs) {
      await convertLinkJob(ctx, job.data as { workspaceId: string; documentId: string });
    }
  });

  await boss.work("run-review-table", { batchSize: concurrency, pollingIntervalSeconds: 2 }, async (jobs) => {
    for (const job of jobs) {
      const d = job.data as { workspaceId: string; reviewTableId: string };
      const { executeReviewTable } = await import("../services/vaults.js");
      await executeReviewTable(ctx, d.workspaceId, d.reviewTableId);
    }
  });

  await boss.work("run-agent", { batchSize: concurrency, pollingIntervalSeconds: 2 }, async (jobs) => {
    for (const job of jobs) {
      const d = job.data as { workspaceId: string; runId: string };
      if (!d.runId) continue;
      const { executeAgentRun } = await import("./agentRunner.js");
      await executeAgentRun(ctx, d.workspaceId, d.runId);
    }
  });

  // scheduler tick for codified agents with a schedule
  await boss.work("agent-scheduler-tick", { batchSize: 1, pollingIntervalSeconds: 60 }, async () => {
    const { scheduleDueAgents } = await import("./agentRunner.js");
    await scheduleDueAgents(ctx);
  });
  await boss.schedule("agent-scheduler-tick", "* * * * *", {});
}
